name: Publish Docker
on:
  push:
    tags:
      - 'v*'
      - 'v*.*'
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/notanormalnerd/python-base
          VERSION=${GITHUB_REF##*/}
          TAGS="${DOCKER_IMAGE}:sha-${GITHUB_SHA::8},${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:latest"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=args::${GITHUB_SHA::8}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.BUILD_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          build-args: GIT_BUILD_VERSION=${{ steps.prep.outputs.args }}
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
      - name: Delete old packages
        uses: smartsquaregmbh/delete-old-packages@v0.2.0
        with:
          keep: 6